"""Add phone column to users

Revision ID: 7088af4d6552
Revises: 
Create Date: 2025-10-02 18:31:13.934748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7088af4d6552'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apartment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contracts_apartment_id'), ['apartment_id'], unique=False)
        batch_op.create_foreign_key(None, 'apartments', ['apartment_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('phone')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contracts_apartment_id'))
        batch_op.drop_column('apartment_id')

    # ### end Alembic commands ###
